language: java
sudo: true #  until travis-ci/apt-package-whitelist#588 is fixed
jdk:
  - openjdk8
addons:
  apt:
    packages:
      - ant-optional
      - ant-contrib
      - libc6:i386
      - icnsutils
      - icoutils
before_install:
  - test -f .git/refs/heads/master || git checkout -b master
  - ./install-deps.sh
install: true
before-script:
 - test -f export_viewer.xml && mv export_viewer.xml build.xml || true
script: ./run_tests.sh
before_deploy:
- ./build_release.sh
env:
  - GIT_NAME="Travis CI" GIT_EMAIL="kingjon3377+travis@gmail.com"
deploy:
  provider: releases
  api_key:
    secure: d9pxgE83U9XC28B9bAm7sIlCqFfWfGQYBMpYj512lmLt4F1wOFvxU1Ltb41ZJzXu/iB+lmzJ80zj7BbxEnkZA6AcTiSHbztjZp3I1n96xOpSjnIK+ju8SAWjjf7tXOsWc6c51kXosnN+ydawABjAZb+yT6lIzwqm0dNY9ZV82PMPgSsvHD8VJzf1FrXqd757Fs7EMKRcXG8SdCxElv3univ0EaDPCfz6dMI4YE0dO9WckZR4Y+SrdKweiSNZDUFFQuCS+zs6NxGk5gt/9sCENXo657hu4Jxb6im0S7N6+kgTF66+2PRWlGsqRdcYK0o/ylz83G2T8hVXmQYf7HqLQQxcSusK6hoYw3Rtuwn/fBUxHoOKY4zsllOv8cmNVYWROW6/+H/M6sHjWiGb4YDqUwv9r2rK/wwxaOH+V02HP1ptcqhjNz2w7PFLvX5uyQVHzZSkGLEJjtY3Kw20xzu4R/8Kli7FrJ+meFlfNvmwxxYCcppaz9hxS1TMqlSEDBnn/SUixmnNvw/YGwkdGw0gMTC6WEYaIIQBoTgqvpHISSLdqExn9pPz4rjm2mDyqdvfjFkvTD7XeOBRk6qdqGudC8MeUStECbgJodCEVJ/DKzx2VPZdCpaeF7OE2sdEb9lvVSNK2T9/Tx6NQrZZ7xBgHBZMJgoMAAZAeyu+Ac1NpLo=
  file_glob: true
  skip_cleanup: true
  file:
    - release/viewer-*.tbz2
    - release/viewer-*.dmg
    - release/viewer-*.exe
    - release/viewer-*.jar
  on:
    repo: kingjon3377/strategicprimer-viewer
    tags: true
