language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
addons:
  apt:
    packages:
      - junit4
      - ant-optional
      - libc6:i386
before_install:
  - ./install-deps.sh
install: ant -Dlaunch4j.dir=./launch4j -Dnullness.jar.path=./org.eclipse.jdt.annotation-1.1.0.jar -Djunit.jar.path=/usr/share/java/junit4.jar -Dwindowmenu.jar.path=./WindowMenu.jar
